// BÓVEDA — registro universal de agentes de IA
// Única fuente de verdad: cada agente que sabe importar BÓVEDA vive aquí,
// con su página oficial de export/autenticación y el formato que acepta.
// types.ts construye los orígenes (Sources) a partir de este registro.

export type AgentCategory = "destacado" | "asistente" | "codigo" | "china";

export interface AgentDef {
  /** id de origen (viaja en el sobre de cada memoria) */
  id: string;
  name: string;
  maker: string;
  category: AgentCategory;
  /** monograma corto para el avatar en la UI */
  mono: string;
  /** dónde pedir el export, en la UI del propio agente */
  hint: string;
  /** deep-link a la página oficial donde el usuario se autentica y pide el export */
  url: string | null;
  /** qué archivo(s) acepta BÓVEDA de este agente */
  formats: string;
  /** cómo llega el dato: zip, json, texto pegado o archivos locales */
  method: "zip" | "json" | "pegar" | "local";
  /** pista por nombre de archivo/carpeta para autodetectar el origen */
  detect?: RegExp;
  /** tiempo típico hasta que llega el archivo tras pedirlo */
  wait?: string;
}

export const CATEGORY_META: Record<AgentCategory, { label: string; desc: string }> = {
  destacado: { label: "Destacados", desc: "Los grandes asistentes de uso masivo" },
  asistente: { label: "Más asistentes", desc: "Meta, Poe, Pi, Character.AI y otros chats" },
  codigo: { label: "Código y desarrollo", desc: "Agentes de programación con historial local o export" },
  china: { label: "IA de China", desc: "Qwen, Kimi, Doubao, Yuanbao, Ernie y GLM" },
};

export const AGENTS: AgentDef[] = [
  /* ── destacados ─────────────────────────────────────────────── */
  {
    id: "chatgpt",
    name: "ChatGPT",
    maker: "OpenAI",
    category: "destacado",
    mono: "GPT",
    hint: "Ajustes → Controles de datos → Exportar datos (llega un .zip por email)",
    url: "https://chatgpt.com/#settings/DataControls",
    formats: ".zip con conversations.json + memories.json, o los .json sueltos",
    method: "zip",
    detect: /chatgpt|openai/i,
    wait: "minutos a 1 día",
  },
  {
    id: "claude",
    name: "Claude",
    maker: "Anthropic",
    category: "destacado",
    mono: "CL",
    hint: "Ajustes → Privacidad → Exportar datos (.zip con conversations.json)",
    url: "https://claude.ai/settings/data",
    formats: ".zip con conversations.json (chat_messages)",
    method: "zip",
    detect: /claude|anthropic/i,
    wait: "instantáneo",
  },
  {
    id: "gemini",
    name: "Gemini",
    maker: "Google",
    category: "destacado",
    mono: "GM",
    hint: "Google Takeout → desmarcar todo → solo «Gemini Apps» (MyActivity.json)",
    url: "https://takeout.google.com",
    formats: "Takeout .zip o MyActivity.json (solo tus prompts)",
    method: "zip",
    detect: /gemini|bard|takeout|google/i,
    wait: "minutos a horas",
  },
  {
    id: "grok",
    name: "Grok",
    maker: "xAI",
    category: "destacado",
    mono: "GK",
    hint: "Ajustes → Datos → Export your data",
    url: "https://grok.com/settings",
    formats: ".zip o .json con conversations (messages/role)",
    method: "zip",
    detect: /grok|xai/i,
    wait: "minutos",
  },
  {
    id: "copilot",
    name: "Copilot",
    maker: "Microsoft",
    category: "destacado",
    mono: "CP",
    hint: "Panel de privacidad de Microsoft → Historial de actividad → Copilot",
    url: "https://account.microsoft.com/privacy",
    formats: ".json/.csv del panel de actividad, o texto pegado",
    method: "json",
    detect: /copilot|microsoft|bing/i,
    wait: "instantáneo",
  },
  {
    id: "perplexity",
    name: "Perplexity",
    maker: "Perplexity AI",
    category: "destacado",
    mono: "PX",
    hint: "Ajustes → Cuenta → Export data (te lo envía por email)",
    url: "https://www.perplexity.ai/settings/account",
    formats: ".zip/.json con threads o library",
    method: "zip",
    detect: /perplexity/i,
    wait: "minutos",
  },
  {
    id: "mistral",
    name: "Le Chat",
    maker: "Mistral AI",
    category: "destacado",
    mono: "MC",
    hint: "Ajustes → Data → Export my data",
    url: "https://chat.mistral.ai/chat/settings",
    formats: ".zip/.json con conversations",
    method: "zip",
    detect: /mistral|lechat/i,
    wait: "instantáneo",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    maker: "DeepSeek",
    category: "destacado",
    mono: "DS",
    hint: "Perfil → Mis datos → Exportar todo (envía .zip por email)",
    url: "https://chat.deepseek.com",
    formats: ".zip con carpetas por chat (conversations.json)",
    method: "zip",
    detect: /deepseek/i,
    wait: "minutos",
  },

  /* ── más asistentes ─────────────────────────────────────────── */
  {
    id: "meta",
    name: "Meta AI",
    maker: "Meta",
    category: "asistente",
    mono: "MA",
    hint: "Centro de cuentas → Tu información → Descargar tu información (actividad de Meta AI)",
    url: "https://accountscenter.facebook.com/info_and_permissions",
    formats: ".json/.html de la descarga de información",
    method: "json",
    detect: /meta|instagram|facebook/i,
    wait: "horas a días",
  },
  {
    id: "poe",
    name: "Poe",
    maker: "Quora",
    category: "asistente",
    mono: "POE",
    hint: "Ajustes → Download data (.zip con tus chats)",
    url: "https://poe.com/settings",
    formats: ".zip/.json con chats y mensajes",
    method: "zip",
    detect: /poe/i,
    wait: "minutos",
  },
  {
    id: "pi",
    name: "Pi",
    maker: "Inflection",
    category: "asistente",
    mono: "PI",
    hint: "Ajustes → Account → Download my data (email con el export)",
    url: "https://pi.ai/settings",
    formats: ".json con conversaciones, o texto pegado",
    method: "json",
    detect: /pi\.ai|inflection/i,
    wait: "1-2 días",
  },
  {
    id: "huggingchat",
    name: "HuggingChat",
    maker: "Hugging Face",
    category: "asistente",
    mono: "HF",
    hint: "Ajustes → Data → Export conversations",
    url: "https://huggingface.co/chat/settings",
    formats: ".json con conversaciones completas",
    method: "json",
    detect: /hugging|openassistant/i,
    wait: "instantáneo",
  },
  {
    id: "characterai",
    name: "Character.AI",
    maker: "Character Technologies",
    category: "asistente",
    mono: "C.AI",
    hint: "Perfil → Settings → Download data (llega por email)",
    url: "https://character.ai/settings",
    formats: ".zip/.json con historial de chats",
    method: "zip",
    detect: /character|c\.ai/i,
    wait: "horas",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    maker: "OpenRouter",
    category: "asistente",
    mono: "OR",
    hint: "Ajustes → Privacy → Request data export",
    url: "https://openrouter.ai/settings",
    formats: ".json con actividad de chat",
    method: "json",
    detect: /openrouter/i,
    wait: "horas",
  },
  {
    id: "youdotcom",
    name: "You.com",
    maker: "You.com",
    category: "asistente",
    mono: "YOU",
    hint: "Ajustes → Account → Export your data",
    url: "https://you.com/settings",
    formats: ".json con threads",
    method: "json",
    detect: /you\.com/i,
    wait: "instantáneo",
  },
  {
    id: "t3chat",
    name: "T3 Chat",
    maker: "Theo — t3.gg",
    category: "asistente",
    mono: "T3",
    hint: "Ajustes → Export data (JSON con un clic)",
    url: "https://t3.chat",
    formats: ".json con threads completos",
    method: "json",
    detect: /t3chat|t3\.chat/i,
    wait: "instantáneo",
  },
  {
    id: "duckai",
    name: "Duck.ai",
    maker: "DuckDuckGo",
    category: "asistente",
    mono: "DDG",
    hint: "Sin cuenta: el historial vive en tu navegador. Abre el chat y cópialo",
    url: "https://duck.ai",
    formats: "texto pegado de la conversación",
    method: "pegar",
    wait: "instantáneo",
  },
  {
    id: "notion",
    name: "Notion AI",
    maker: "Notion",
    category: "asistente",
    mono: "NO",
    hint: "Ajustes → Exportar contenido → Todo el workspace (Markdown & CSV)",
    url: "https://www.notion.so/my-settings",
    formats: ".zip/.md con páginas y conversaciones",
    method: "zip",
    detect: /notion/i,
    wait: "minutos",
  },

  /* ── código y desarrollo ────────────────────────────────────── */
  {
    id: "claude-code",
    name: "Claude Code",
    maker: "Anthropic",
    category: "codigo",
    mono: "CC",
    hint: "Historial local: ~/.claude/projects/ → archivos .jsonl por sesión",
    url: null,
    formats: ".jsonl de sesión directamente",
    method: "local",
    detect: /claude.?code|\.claude/i,
    wait: "local",
  },
  {
    id: "cursor",
    name: "Cursor",
    maker: "Anysphere",
    category: "codigo",
    mono: "CUR",
    hint: "Los chats viven en una base local; copia la conversación y pégala aquí",
    url: null,
    formats: "texto pegado o .json/.md",
    method: "pegar",
    detect: /cursor/i,
    wait: "local",
  },
  {
    id: "windsurf",
    name: "Windsurf",
    maker: "Codeium",
    category: "codigo",
    mono: "WS",
    hint: "Historial local (~/.codeium/windsurf); copia la conversación y pégala",
    url: null,
    formats: "texto pegado o .json/.md",
    method: "pegar",
    detect: /windsurf|codeium/i,
    wait: "local",
  },
  {
    id: "cline",
    name: "Cline",
    maker: "Cline (VS Code)",
    category: "codigo",
    mono: "CLN",
    hint: "Panel de Cline → Export task history (.json/.md por tarea)",
    url: null,
    formats: ".json/.md de tareas",
    method: "json",
    detect: /cline/i,
    wait: "local",
  },
  {
    id: "gemini-cli",
    name: "Gemini CLI",
    maker: "Google",
    category: "codigo",
    mono: "GCLI",
    hint: "Historial local: ~/.gemini/tmp/ → session-*.json",
    url: null,
    formats: ".json de sesión",
    method: "local",
    detect: /gemini.?cli|\.gemini/i,
    wait: "local",
  },
  {
    id: "aider",
    name: "Aider",
    maker: "Aider",
    category: "codigo",
    mono: "AID",
    hint: "Archivo de historial en tu repo: .aider.chat.history.md",
    url: null,
    formats: ".md de historial directamente",
    method: "local",
    detect: /aider/i,
    wait: "local",
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    maker: "GitHub",
    category: "codigo",
    mono: "GH",
    hint: "GitHub → Settings → Account data → Request data archive",
    url: "https://github.com/settings/data",
    formats: ".zip del archivo de datos de GitHub",
    method: "zip",
    detect: /github/i,
    wait: "horas a días",
  },

  /* ── IA de China ────────────────────────────────────────────── */
  {
    id: "qwen",
    name: "Qwen",
    maker: "Alibaba",
    category: "china",
    mono: "QW",
    hint: "Ajustes → Data → Export chat history",
    url: "https://chat.qwen.ai",
    formats: ".json/.zip con chats",
    method: "json",
    detect: /qwen|tongyi/i,
    wait: "instantáneo",
  },
  {
    id: "kimi",
    name: "Kimi",
    maker: "Moonshot AI",
    category: "china",
    mono: "KIM",
    hint: "Perfil → Data management → Export data",
    url: "https://www.kimi.com",
    formats: ".json/.zip con chats",
    method: "json",
    detect: /kimi|moonshot/i,
    wait: "minutos",
  },
  {
    id: "glm",
    name: "GLM / Z.ai",
    maker: "Zhipu AI",
    category: "china",
    mono: "GLM",
    hint: "Ajustes → Datos → Exportar conversaciones",
    url: "https://chat.z.ai",
    formats: ".json/.zip con chats",
    method: "json",
    detect: /glm|z\.ai|chatglm|zhipu/i,
    wait: "instantáneo",
  },
  {
    id: "doubao",
    name: "Doubao",
    maker: "ByteDance",
    category: "china",
    mono: "DB",
    hint: "Ajustes → Data → Solicitud de exportación de historial",
    url: "https://www.doubao.com",
    formats: ".json/.zip con chats, o texto pegado",
    method: "pegar",
    detect: /doubao/i,
    wait: "horas",
  },
  {
    id: "yuanbao",
    name: "Yuanbao",
    maker: "Tencent",
    category: "china",
    mono: "YB",
    hint: "Ajustes → Privacidad → Exportar historial de conversaciones",
    url: "https://yuanbao.tencent.com",
    formats: ".json/.zip con chats, o texto pegado",
    method: "pegar",
    detect: /yuanbao|tencent/i,
    wait: "horas",
  },
  {
    id: "ernie",
    name: "Ernie Bot",
    maker: "Baidu",
    category: "china",
    mono: "ERN",
    hint: "Ajustes → Privacidad → Descargar tus datos",
    url: "https://yiyan.baidu.com",
    formats: ".json/.zip con chats, o texto pegado",
    method: "pegar",
    detect: /ernie|yiyan|baidu/i,
    wait: "horas",
  },
];

/** Mapa id → definición. */
export const AGENT_BY_ID: Record<string, AgentDef> = Object.fromEntries(
  AGENTS.map((a) => [a.id, a]),
);

/** Adivina el agente por un nombre de archivo o carpeta raíz del export. */
export function detectAgentFromName(name: string): AgentDef | null {
  for (const a of AGENTS) {
    if (a.detect && a.detect.test(name)) return a;
  }
  return null;
}
